language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
# command to run tests
before_script: python setup.py build_ext --inplace
script: nosetests --with-coverage --cover-package=schemamessages
after_success:
  coveralls